### ISSUE TITLE
CMA Access Token is invalid

### ISSUE THREAD

**Issue by mariobodemann** [contentful/slash-developers#186]
Hey, 

if I follow https://github.com/contentful/slash-developers/blob/master/apiary/cma.apib#L128, on http://docs.contentfulcma.apiary.io/#reference/spaces/spaces-collection/get-all-entries-of-a-space?console=1 I recieve 

```
{
  "sys": {
    "type": "Error",
    "id": "AccessTokenInvalid"
  },
  "message": "The access token you sent could not be found or is invalid.",
  "requestId": "content-api:y0i7FWHl6gYQS8qsigIKI"
}
```

Response on all the CMA samples. Any ideas?

**Comment by gaapt** [comment]
I don't think there's a simple workaround for this, as a valid token would enable PUT/POST/DELETE requests to the space.

**Comment by mariobodemann** [comment]
I would see some options: 

* reset the example space every so often (every hour?), so changes are not there for too long.
* do not offer the console for CMA at all
* do not put a token in the console, so the user thinks this might work

**Comment by gaapt** [comment]
1-2 look like good options. 

Only problem I see is that, on resetting the space every hour, there could be issues with GET requests.

**Comment by neonichu** [comment]
We would need to reset after every request to actually ensure the described requests work, though, because most of them will depend on a very specific server state and even that would not address concurrent requests. IMO, it will be even more confusing when there can be various different errors.

Disabling would mean there's no place to see JSON responses, which right now is possible when people use the mock server. We could however limit the console to the mock server.

Another option might be having a magic token which leads to emission of a different error message that tells the user what's going on?

**Comment by floelhoeffel** [comment]
How about a token which can only read stuff? Now powered by RnP :)

**Comment by realityking** [comment]
We've disabled the console for the CMA as there's no other sensible solution.
